version: "3.8"

services:
  php_fpm:
      build: .
      container_name: chess_api_php_fpm
      ports:
        - 8000:8000
      restart: always
      working_dir: /usr/share/nginx/chess-api
      volumes:
          - ./:/usr/share/nginx/chess-api
          - ./docker/php/8.0/cli/php.ini:/usr/local/etc/php/php.ini
