site_name: PHP Chess API
pages:
  - Chess API for Web Apps: index.md
  - GET /annotations/games: get-annotations-games.md
  - GET /autocomplete/event: get-autocomplete-event.md
  - GET /autocomplete/player: get-autocomplete-player.md
  - GET /stats/opening: get-stats-opening.md
  - POST /download/image: post-download-image.md
  - POST /download/mp4: post-download-mp4.md
  - POST /heuristics: post-heuristics.md
  - POST /search: post-search.md
  - POST /stats/event: post-stats-event.md
  - POST /stats/player: post-stats-player.md
  - POST /play/rav: post-play-rav.md
theme: readthedocs
