site_name: Chess API
pages:
  - Chess API for Web Apps: index.md
  - GET /autocomplete: get-autocomplete.md
  - GET /stats/opening: get-stats-opening.md
  - POST /download/image: post-download-image.md
  - POST /download/mp4: post-download-mp4.md
  - POST /engine/stockfish: post-engine-stockfish.md
  - POST /grandmaster: post-engine-stockfish.md
  - POST /opening: post-opening.md
  - POST /play/lan: post-play-lan.md
theme: readthedocs
