api_docs:
    path:       /api/docs
    controller: ChessApi\Controller\DocsController::index
    methods:    GET

api_grandmaster:
    path:       /api/grandmaster
    controller: ChessApi\Controller\GrandmasterController::index
    methods:    POST

api_opening:
    path:       /api/opening
    controller: ChessApi\Controller\OpeningController::index
    methods:    POST

api_play:
    path:       /api/play
    controller: ChessApi\Controller\PlayController::index
    methods:    POST

api_download_mp4:
    path:       /api/download_mp4
    controller: ChessApi\Controller\DownloadMp4Controller::index
    methods:    POST

api_download_image:
    path:       /api/download_image
    controller: ChessApi\Controller\DownloadImageController::index
    methods:    POST

api_tournament:
    path:       /api/tournament
    controller: ChessApi\Controller\TournamentController::index
    methods:    POST

api_search:
    path:       /api/search
    controller: ChessApi\Controller\SearchController::index
    methods:    POST
