api_docs:
    path:       /api/docs
    controller: ChessApi\Controller\DocsController::index
    methods:    GET

api_grandmaster:
    path:       /api/grandmaster
    controller: ChessApi\Controller\GrandmasterController::index
    methods:    POST

api_opening:
    path:       /api/opening
    controller: ChessApi\Controller\OpeningController::index
    methods:    POST

api_play:
    path:       /api/play
    controller: ChessApi\Controller\PlayController::index
    methods:    POST
