api_annotations_games:
    path:       /api/annotations/games
    controller: ChessApi\Controller\AnnotationsGamesController::index
    methods:    GET

api_autocomplete_event:
    path:       /api/autocomplete/event
    controller: ChessApi\Controller\AutocompleteEventController::index
    methods:    GET

api_autocomplete_player:
    path:       /api/autocomplete/player
    controller: ChessApi\Controller\AutocompletePlayerController::index
    methods:    GET

api_download_image:
    path:       /api/download/image
    controller: ChessApi\Controller\DownloadImageController::index
    methods:    POST

api_download_mp4:
    path:       /api/download/mp4
    controller: ChessApi\Controller\DownloadMp4Controller::index
    methods:    POST

api_engine_stockfish:
    path:       /api/engine/stockfish
    controller: ChessApi\Controller\EngineStockfishController::index
    methods:    POST

api_grandmaster:
    path:       /api/grandmaster
    controller: ChessApi\Controller\GrandmasterController::index
    methods:    POST

api_heuristics:
    path:       /api/heuristics
    controller: ChessApi\Controller\HeuristicsController::index
    methods:    POST

api_opening:
    path:       /api/opening
    controller: ChessApi\Controller\OpeningController::index
    methods:    POST

api_play_lan:
    path:       /api/play/lan
    controller: ChessApi\Controller\PlayLanController::index
    methods:    POST

api_play_pgn:
    path:       /api/play/pgn
    controller: ChessApi\Controller\PlayPgnController::index
    methods:    POST

api_play_rav:
    path:       /api/play/rav
    controller: ChessApi\Controller\PlayRavController::index
    methods:    POST

api_search:
    path:       /api/search
    controller: ChessApi\Controller\SearchController::index
    methods:    POST

api_stats_event:
    path:       /api/stats/event
    controller: ChessApi\Controller\StatsEventController::index
    methods:    POST

api_stats_opening:
    path:       /api/stats/opening
    controller: ChessApi\Controller\StatsOpeningController::index
    methods:    GET

api_stats_player:
    path:       /api/stats/player
    controller: ChessApi\Controller\StatsPlayerController::index
    methods:    POST
